@startuml s3
autoactivate on 
hide footbox
actor Akteur
participant "student: Student" as Student
participant "mainSubject: Subject" as Subject


    Akteur -> Student : printNameOfMainSubject()
    Student -> Subject : name()
    return name
@enduml
